class Locators:

    def __init__(self):
# Локаторы кликабельные
        """ Locators of main page"""
        self.button_sign_in = "//button[@id='sign-up-in']"
        self.line_email = "//input[@name='login_email']"
        self.line_password = "//input[@name='login_password']"
        self.button_sign_come_in = "//div[@class='clearfix']/button[@type='submit']"
        self.button_foto_akk = "//img[@alt = 'Фотография аккаунта']"
        self.button_settings_akk = "//a[text()='Настройки']"
        self.button_change_foto = "//div[@class='account-page-module  account-key-value-block preference-picture-row']//button[@class='mc-tertiary-link-button account-key-value-block__link']"
        self.download_foto = "//input[@type='file']"
        self.button_gotovo = "//span[text()='Готово']"
        self.button_change_name = "//div[@class='account-page-module  account-key-value-block preference-name-row']//span[text()='Изменить']"
        self.line_fname = "//input[@name='fname']"
        self.line_lname = "//input[@name='lname']"
        self.button_change_title = "//button[@class='button-primary dbmodal-button']"
        self.selector_data = "//span[@class='mc-dropdown-button-content']"
        self.line_format_data_MM_DD_YYYY = "//span[text()='ММ / ДД / ГГГГ']"
        self.button_my_files = "//a[@id='files']"
        self.button_create_folder = "//div[text()='Создать папку']"
        self.line_name_folder = "//input[@id='new_folder_name_input']"
        self.button_create = "//button[@class='button-primary dbmodal-button']"
        self.button_back_preview = "//span[@class='react-title-bar__close-content']"
        self.button_over_actions_for_file = "//div[@class='browse-overflow-menu']//span[@aria-label='Другие действия']"
        self.button_rename_file = "//span[text()='Переименовать']"
        self.line_rename_file = "//form[@class='u-pad-right-xs']//input[2]"
        self.button_share = "//div[@class='mc-popover-content-background']//span[text()='Поделиться']"
        self.button_create_link = "//span[text()='Создать ссылку']"
        self.button_copy_link = "//span[text()='Копировать ссылку']"
        self.line_send_email = "//input[@class='mc-tokenized-input-input']"
        self.button_share_to_email = "//button[@class='scl-sharing-modal-footer-inband__button mc-button mc-button-primary']//span[text()='Поделиться']"
        self.line_search = "//input[@id='fakebox-input']"

# Локаторы для явного ожидания
        """ Locators of profile page"""
        self.login_successful = "//h1[text()='Домашняя страница']"
        self.personal_akk = "//h1[text()='Личный аккаунт']"
        self.add_foto_akk = "//div[@class='top-text']"
        self.looks_great = "//span[text()='Прекрасно смотрится!']"
        self.avatar_ok = "//button[@class='mc-tertiary-link-button account-key-value-block__link']//span[text()='Удалить']"
        self.name_ok = "//div//span[text()='Test Task']"
        self.data_ok = "//span[text()='ММ / ДД / ГГГГ']"
        self.location_files = "//span[@class='ue-effect-container uee-PathBreadcrumbs-HomeTitle']"
        self.window_create_folder = "//div[@class='o-flag__flex u-pad-left-s u-pad-right-s']"
        self.folder_created_ok = "//span[text()='New folder']"
        self.file_download = "//input[@id]"
        self.file_is_downloaded = "//span[text()='Task for testing.docx']"
        self.view_content = "//*[contains(text(), 'Написать')]"
        self.window_send_file = "//div[text()='Кому:']"
        self.message_link_ready = "//span[text()=', у кого есть ссылка, смогут ']"
        self.message_message_send_is_complete = "//p[text()='Предоставлен доступ к ']"

        self.button_close_1 = "//span[text()='Закрыть']"